// This file is auto-generated by @hey-api/openapi-ts

export const TokenRefreshRequestSchema = {
    type: 'object',
    properties: {
        refreshToken: {
            type: 'string'
        }
    },
    required: ['refreshToken']
} as const;

export const ApiResponseDTOTokenRefreshResponseSchema = {
    type: 'object',
    properties: {
        error: {
            type: 'boolean'
        },
        message: {
            type: 'string'
        },
        code: {
            type: 'integer',
            format: 'int32'
        },
        data: {
            '$ref': '#/components/schemas/TokenRefreshResponse'
        }
    },
    required: ['code', 'error', 'message']
} as const;

export const TokenRefreshResponseSchema = {
    type: 'object',
    properties: {
        accessToken: {
            type: 'string'
        },
        refreshToken: {
            type: 'string'
        }
    },
    required: ['accessToken', 'refreshToken']
} as const;

export const LogoutRequestSchema = {
    type: 'object',
    properties: {
        accessToken: {
            type: 'string'
        },
        refreshToken: {
            type: 'string'
        }
    },
    required: ['accessToken', 'refreshToken']
} as const;

export const LoginRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    },
    required: ['email', 'password']
} as const;

export const ApiResponseDTOLoginResponseSchema = {
    type: 'object',
    properties: {
        error: {
            type: 'boolean'
        },
        message: {
            type: 'string'
        },
        code: {
            type: 'integer',
            format: 'int32'
        },
        data: {
            '$ref': '#/components/schemas/LoginResponse'
        }
    },
    required: ['code', 'error', 'message']
} as const;

export const LoginResponseSchema = {
    type: 'object',
    properties: {
        accessToken: {
            type: 'string'
        },
        refreshToken: {
            type: 'string'
        }
    },
    required: ['accessToken', 'refreshToken']
} as const;

export const ApiResponseDTOListResponseHousingSchema = {
    type: 'object',
    properties: {
        error: {
            type: 'boolean'
        },
        message: {
            type: 'string'
        },
        code: {
            type: 'integer',
            format: 'int32'
        },
        data: {
            '$ref': '#/components/schemas/ListResponseHousing'
        }
    },
    required: ['code', 'error', 'message']
} as const;

export const HousingSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        longitude: {
            type: 'number',
            format: 'double'
        },
        latitude: {
            type: 'number',
            format: 'double'
        },
        housingMedianAge: {
            type: 'number',
            format: 'double'
        },
        totalRooms: {
            type: 'number',
            format: 'double'
        },
        totalBedrooms: {
            type: 'number',
            format: 'double'
        },
        population: {
            type: 'number',
            format: 'double'
        },
        households: {
            type: 'number',
            format: 'double'
        },
        medianIncome: {
            type: 'number',
            format: 'double'
        },
        medianHouseValue: {
            type: 'number',
            format: 'double'
        },
        oceanProximity: {
            type: 'string'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['createdAt', 'households', 'housingMedianAge', 'latitude', 'longitude', 'medianHouseValue', 'medianIncome', 'oceanProximity', 'population', 'totalBedrooms', 'totalRooms', 'updatedAt']
} as const;

export const ListResponseHousingSchema = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Housing'
            }
        },
        total: {
            type: 'integer',
            format: 'int64'
        },
        page: {
            type: 'integer',
            format: 'int32'
        },
        size: {
            type: 'integer',
            format: 'int32'
        },
        pages: {
            type: 'integer',
            format: 'int32'
        },
        columns: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: ['columns', 'data', 'page', 'pages', 'size', 'total']
} as const;

export const UserInfoResponseSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        roles: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        username: {
            type: 'string'
        }
    },
    required: ['email', 'roles', 'username']
} as const;