// This file is auto-generated by @hey-api/openapi-ts

import type { GetHousingListResponse } from './types.gen';

const housingSchemaResponseTransformer = (data: any) => {
    if (data.id) {
        data.id = BigInt(data.id.toString());
    }
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const listResponseHousingSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => {
        return housingSchemaResponseTransformer(item);
    });
    data.total = BigInt(data.total.toString());
    return data;
};

const apiResponseDtoListResponseHousingSchemaResponseTransformer = (data: any) => {
    if (data.data) {
        data.data = listResponseHousingSchemaResponseTransformer(data.data);
    }
    return data;
};

export const getHousingListResponseTransformer = async (data: any): Promise<GetHousingListResponse> => {
    data = apiResponseDtoListResponseHousingSchemaResponseTransformer(data);
    return data;
};