spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
antbiz:
  jwt:
    signing-key: ${JWT_SIGNING_KEY}
    validate-key: ${JWT_VALIDATE_KEY}
    issuer: ${JWT_ISSUER}
    access-token-validity: 10800 # 원래 900초
    refresh-token-validity: 2592000
  etc:
    frontend: ${FRONTEND_NAME}
    host: ${HOST_NAME}
snapadmin:
  enabled: true
  baseUrl: admin
  models-package: org.antbiz.antbiz_framework.framework.model,org.antbiz.backend_test.model
  brand-name: Antbiz